### PR TITLE
Correct types for Event

### PR DESCRIPTION
**Pull request by orsinium**
I had a few minutes to make it kinda work. I'm not happy that mypy can't infer the type for type variable automagically, though, but at least the annotation is simpler now.

### CODE REVIEW

**Comment by AstraLuma** [comment]
I'll have to refactor those tests.

One thing I'm not totally sold on is the lack of support for keyword argument support. But that's pretty week in general (since you have to define an entire protocol to do so).

**Comment by orsinium** [comment]
You can make a protocol, yes. The point is that if you don't define in terms of the event holder type what exactly callable you expect handlers to be, annotating the event gets tedious. In this implementation, however, all you need to specify is the event holder type, which is much shorter. My goal was to make mypy to infer this type, which should be possible, but somehow it fails to do so.

**Comment by AstraLuma** [comment]
Ok, so I finally got a chance to re-read this, and it only handles no-argument events?

**Comment by orsinium** [comment]
I guess so. Sorry, I don't have enough context on the project purpose and goals to bring a more meaningful contribution.

**Comment by AstraLuma** [comment]
https://peps.python.org/pep-0646/

**Pull request closed without merging**
